# Generated by Django 3.0.5 on 2020-04-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='autthor',
            new_name='author',
        ),
    ]
